### ISSUE TITLE
Bulleted Lists Not Appearing Correctly

### ISSUE THREAD

**Issue by mjsamberg** [TheFridayInstitute/moodle-theme_fridayinstitute#7]
Bulleted list hanging indents not working properly.

![ii_159d1bed864d01ad](https://cloud.githubusercontent.com/assets/1527123/22265431/fc2f8972-e249-11e6-9781-8c70d2bb672a.png)

**Comment by mjsamberg** [comment]
Updated and moved to staging. Transferring to @maday4 for review.

**Comment by maday4** [comment]
- Catalog page - (IE, Chrome, & Firefox) - Text in body and within accordion menus aligns but list bullets/numbers are now in the margins. The default text indention for numbered and unnumbered lists has disappeared. 
![bullets_catalog](https://cloud.githubusercontent.com/assets/21264568/22303819/f59939be-e302-11e6-9651-52954ea96fc8.png)

- Course home page - (IE, Chrome, Firefox) - In body, text aligns, bullets are indented (as opposed to out in the margin) but indention is reduced. Default bullets now look like disc-style lists. 

![bullets_homepg_disc](https://cloud.githubusercontent.com/assets/21264568/22309690/54c62e58-e31a-11e6-8c22-4e46e76b7d2f.png)
![bullets_homepg_original](https://cloud.githubusercontent.com/assets/21264568/22309696/582b5be0-e31a-11e6-9fc2-6e84869b4d85.png)


- Also in course home page - (Chrome, IE, Firefox) - In accordions, bulleted lists in section descriptions have disappeared. 

![bullets_homepg_accordion](https://cloud.githubusercontent.com/assets/21264568/22310604/cd552e02-e31d-11e6-9514-5c8658c2751f.png)
![bullets_homepg_accordion_original](https://cloud.githubusercontent.com/assets/21264568/22310610/d0483488-e31d-11e6-9fdb-a760077bf42a.png)


- Course sub-pages - (Chrome, IE) - In panels, bullets/numbers no longer indented -- are outside text margin and partially cut off by panel border. (happens in page modules, but, strangely, not in videoresource text below video)
![bullets_paneldiv](https://cloud.githubusercontent.com/assets/21264568/22307822/8c247966-e312-11e6-8d6b-03e7b7d0d8c4.png)

- Also in course sub-pages - In section-content, bullets/numbers have disappeared for top level of nested lists, but not the subsidiaries.
![bullets_ordinallist_sectiondiv](https://cloud.githubusercontent.com/assets/21264568/22308565/7e474c6c-e315-11e6-90c1-2dc3f88af0e8.png)
![bullets_ordinallist_sectiondiv_original](https://cloud.githubusercontent.com/assets/21264568/22308570/8425956c-e315-11e6-897f-6b92b262a92a.png)

- Sidebars -- appear ok in Chrome, IE, and Firefox

- Menubars -- appear ok in Chrome, IE, and Firefox

**Comment by mjsamberg** [comment]
@maday4 Should be corrected now, along with updates per NCSU branding.

**Comment by maday4** [comment]
Revisted all of the above issues in Chrome, IE, and Firefox. Also checked to see if resizing a page caused anything funky. Everything looks good!
